export const GETTER_CONVERSATIONS = 'GETTER_CONVERSATIONS'
export const GETTER_MESSAGES = 'GETTER_MESSAGES'
export const SET_SIDEBAR = 'SET_SIDEBAR'
export const SET_NAVLOADER = 'SET_NAVLOADER'

export default {
  GETTER_CONVERSATIONS,
  GETTER_MESSAGES,
  SET_SIDEBAR,
  SET_NAVLOADER
}
