export const GET_MESSAGE = 'GET_MESSAGE';
export const SET_MESSAGES = 'SET_MESSAGES';

export const SET_SIDEBAR = 'SET_SIDEBAR'
export const SET_NAVLOADER = 'SET_NAVLOADER'
export const SET_CONTACTS = 'SET_CONTACTS'
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS'
export const SET_MODAL_ADD_CONTACT = 'SET_MODAL_ADD_CONTACT'
